### ISSUE TITLE
galsim config/flat.yaml produces GalSimConfigError 

### ISSUE THREAD

**Issue by jchiang87** [LSSTDESC/imSim#322]
Here's what I'm getting using `config/flat.yaml` with current main:
```
$ galsim flat.yaml 
Reading config file flat.yaml
Overriding default configuration file with /opt/lsst/software/stack/stack/miniconda3-py38_4.9.2-5.1.0/Linux64/dustmaps_cachedata/g41a3ec361e+62d12e78cb/config/.dustmapsrc
Reading TreeRing file /home/jchiang/work/DESC/imSim/imsim/data/tree_ring_data/tree_ring_parameters_2018-04-26.txt
Start file 0 = flats/flat_eimage_00001-r-R22_S11-det094.fits
Exception caught for file 0 = flats/flat_eimage_00001-r-R22_S11-det094.fits
File flats/flat_eimage_00001-r-R22_S11-det094.fits not written.
Traceback (most recent call last):
  File "/opt/lsst/software/stack/conda/miniconda3-py38_4.9.2/envs/lsst-scipipe-5.1.0/bin/galsim", line 8, in <module>
    sys.exit(run_main())
  File "/opt/lsst/software/stack/conda/miniconda3-py38_4.9.2/envs/lsst-scipipe-5.1.0/lib/python3.10/site-packages/galsim/main.py", line 229, in run_main
    main(sys.argv[1:])
  File "/opt/lsst/software/stack/conda/miniconda3-py38_4.9.2/envs/lsst-scipipe-5.1.0/lib/python3.10/site-packages/galsim/main.py", line 224, in main
    process_config(all_config, args, logger)
  File "/opt/lsst/software/stack/conda/miniconda3-py38_4.9.2/envs/lsst-scipipe-5.1.0/lib/python3.10/site-packages/galsim/main.py", line 202, in process_config
    Process(config, logger, njobs=args.njobs, job=args.job, new_params=new_params,
  File "/opt/lsst/software/stack/conda/miniconda3-py38_4.9.2/envs/lsst-scipipe-5.1.0/lib/python3.10/site-packages/galsim/config/process.py", line 293, in Process
    config_out = BuildFiles(nfiles, config, file_num=start, logger=logger,
  File "/opt/lsst/software/stack/conda/miniconda3-py38_4.9.2/envs/lsst-scipipe-5.1.0/lib/python3.10/site-packages/galsim/config/output.py", line 164, in BuildFiles
    results = MultiProcess(nproc, orig_config, BuildFile, tasks, 'file',
  File "/opt/lsst/software/stack/conda/miniconda3-py38_4.9.2/envs/lsst-scipipe-5.1.0/lib/python3.10/site-packages/galsim/config/util.py", line 888, in MultiProcess
    result = job_func(**kwargs)
  File "/opt/lsst/software/stack/conda/miniconda3-py38_4.9.2/envs/lsst-scipipe-5.1.0/lib/python3.10/site-packages/galsim/config/output.py", line 248, in BuildFile
    data = builder.buildImages(output, config, file_num, image_num, obj_num, ignore, logger)
  File "/home/jchiang/work/DESC/imSim/imsim/ccd.py", line 101, in buildImages
    image = galsim.config.BuildImage(base, image_num, obj_num, logger=logger)
  File "/opt/lsst/software/stack/conda/miniconda3-py38_4.9.2/envs/lsst-scipipe-5.1.0/lib/python3.10/site-packages/galsim/config/image.py", line 265, in BuildImage
    SetupConfigImageSize(config, xsize, ysize, logger)
  File "/opt/lsst/software/stack/conda/miniconda3-py38_4.9.2/envs/lsst-scipipe-5.1.0/lib/python3.10/site-packages/galsim/config/image.py", line 212, in SetupConfigImageSize
    wcs = BuildWCS(image, 'wcs', config, logger)
  File "/opt/lsst/software/stack/conda/miniconda3-py38_4.9.2/envs/lsst-scipipe-5.1.0/lib/python3.10/site-packages/galsim/config/wcs.py", line 103, in BuildWCS
    wcs = builder.buildWCS(param, base, logger)
  File "/home/jchiang/work/DESC/imSim/imsim/batoid_wcs.py", line 490, in buildWCS
    kwargs, safe = galsim.config.GetAllParams(config, base, req=req, opt=opt)
  File "/opt/lsst/software/stack/conda/miniconda3-py38_4.9.2/envs/lsst-scipipe-5.1.0/lib/python3.10/site-packages/galsim/config/value.py", line 411, in GetAllParams
    get = CheckAllParams(config,req,opt,single,ignore)
  File "/opt/lsst/software/stack/conda/miniconda3-py38_4.9.2/envs/lsst-scipipe-5.1.0/lib/python3.10/site-packages/galsim/config/value.py", line 392, in CheckAllParams
    raise GalSimConfigError("Unexpected attribute %s found"%(key))
galsim.errors.GalSimConfigError: Unexpected attribute rotTelPos found
```
I get the same outcome with `config/flat_with_sed.yaml`.

**Comment by jchiang87** [comment]
Fixed by #335
